# input
inputs:
  data: /home/stefano/Desktop/cernbox/checks/dmeson_phi/AO2D_2050.root
  fTreeDmeson: DF_2336986335323680/O2hfcharmcandlite

# cuts
bdt_bkg_bins: [0.004, 0.004, 0.008, 0.018, 0.015, 0.03, 0.08, 0.15]
bdt_sgn_bins: [0.010, 0.010, 0.010, 0.010, 0.010, 0.01, 0.01, 0.01]
mass_mins: [1.70, 1.70, 1.70, 1.70, 1.70, 1.70, 1.70, 1.70] #, 0.7, 1.0, 1.5]
mass_maxs: [2.05, 2.05, 1.98, 1.98, 1.98, 2.05, 2.05, 2.05] #, 1.0, 1.5, 2.0]
pt_mins: [0, 2, 4, 6, 8, 10, 12] #, 0.7, 1.0, 1.5]
pt_maxs: [2, 4, 6, 8, 10, 12, 24] #, 1.0, 1.5, 2.0]
cuts:
  key: Null # key to be used for the cuts, if None, the cuts are not applied
  bins_min: [0, 0, 0, 0, 0, 0, 0, 0] #, 0, 0, 0]
  bins_max: [0.001, 0.001, 0.08, 0.001, 0.001, 0.1, 0.001, 0.001] #, 0.001, 0.001, 0.001]
cent_bins: [0, 100]
occ_bins: [ 
            [0, 5000],
            [0, 6000],
          ]

# fit
fit_config:
  sgn_func: "gaussian"
  bkg_func: "expo"
  mean: 1.87
  sigma: 0.08

# output
output:
  dir: ./output
  suffix: "2050"
